default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: paiementgenial_development

test:
  <<: *default
  database: paiementgenial_test

production:
  <<: *default
  encoding: unicode
  database: paiementgenial_production
  username: user_cb048df7a69e
  password: <%= ENV["DATABASE_PASSWORD"] %>
